public class Main {
    public static void main(String[] args) {
        var dog = 8.0;
        System.out.println(dog);
        var cat = 3.6;
        System.out.println(cat);
        var paper = 763789;
        System.out.println(paper);
        dog = dog +4;
        System.out.println(dog);
        cat = cat + 4;
        System.out.println(cat);
        paper = paper + 4;
        System.out.println(paper);
        dog = dog - 3.5;
        System.out.println(dog);
        cat = cat - 1.6;
        System.out.println(cat);
        paper = paper - 7639;
        System.out.println(paper);
        var friend = 19;
        System.out.println(friend);
        friend = friend * 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        var boxer1Weight = 78.2;
        var boxer2Weight = 82.7;
        var boxersWeight = boxer1Weight + boxer2Weight;
        System.out.println(boxersWeight);
        var differenceWeight = boxer1Weight- boxer2Weight;
        System.out.println(differenceWeight);
        var oneWay = boxer2Weight- boxer1Weight;
        System.out.println(oneWay);
        var twoWay = boxer2Weight % boxer1Weight;
        System.out.println(twoWay);
        var hoursWork = 640;
        var oneWorker = 8;
        var workers = hoursWork / oneWorker;
        System.out.println("Всего работников в компании - " + workers  + " человек. ");
        var allWorkers = workers + 94;
        var allHours = allWorkers * oneWorker;
        System.out.println("Если в компании работает " + allWorkers + " человек, то всего " + allHours + " часов работы может быть поделено между сотрудниками. ");
    }
}